spring:
  application:
    name: XXX
  datasource:
    url: jdbc:mysql://localhost:3306/cjn
    username: root
    password: spnor87858389
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: edu.jxau.cjn.infrastructure.DefaultPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  main:
    web-application-type: servlet
  freemarker:
    enabled: true
    request-context-attribute: request
  http:
    converters:
      preferred-json-mapper: jackson
  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - classpath:/META-INF/resources/
      - file:d://upload/
  servlet:
    multipart:
      max-file-size: 20MB
  mail:
    host: smtp.qq.com
    username: 2364672979@qq.com
    password: 2324eewf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
logging:
  level:
    org.apache: info
    org.springframework: debug
server:
  port: 7777
debug: true
