spring:
  application:
    name: XXX
  datasource:
    url: jdbc:mysql://localhost:3306/cjn
    username: root
    password: spnor87858389
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  main:
    web-application-type: servlet
  freemarker:
    enabled: true
    request-context-attribute: request
  http:
    converters:
      preferred-json-mapper: jackson
  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - classpath:/META-INF/resources/
      - file:d://upload/
logging:
  level:
    org.apache: info
    org.springframework: debug
server:
  port: 8888