spring:
  application:
    name: cjn-schedule-application
  datasource:
    url: jdbc:mysql://localhost:3306/cjn
    username: root
    password: spnor87858389
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: edu.jxau.cjn.infrastructure.DefaultPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mail:
    host: smtp.qq.com
    username: 2364672979@qq.com
    password: mptcvumnvbtldjig
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

simpleJob:
  cron: 0 0/1 * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Shanghai
